#!/usr/bin/env bash
git clone https://github.com/xiaozhiliaoo/k8s-practice
git clone https://github.com/xiaozhiliaoo/docker-practice
git clone https://github.com/xiaozhiliaoo/linux-practice
git clone https://github.com/xiaozhiliaoo/thinkinginjava-practice
git clone https://github.com/xiaozhiliaoo/go-practice
git clone https://github.com/xiaozhiliaoo/python-practice
git clone https://github.com/xiaozhiliaoo/javascript-practice
git clone https://github.com/xiaozhiliaoo/designpattern-practice
git clone https://github.com/xiaozhiliaoo/refactor-practice
git clone https://github.com/xiaozhiliaoo/websocket-practice
git clone https://github.com/xiaozhiliaoo/lambda-practice
git clone https://github.com/xiaozhiliaoo/tdd-practice
git clone https://github.com/xiaozhiliaoo/test-practice
git clone https://github.com/xiaozhiliaoo/servlet-practice
git clone https://github.com/xiaozhiliaoo/jdk-practice
git clone https://github.com/xiaozhiliaoo/cache-practice
git clone https://github.com/xiaozhiliaoo/task-schedule-practice
git clone https://github.com/xiaozhiliaoo/cicd-practice
git clone https://github.com/xiaozhiliaoo/j2ee-practice
git clone https://github.com/xiaozhiliaoo/common-practice
git clone https://github.com/xiaozhiliaoo/effective-java-practice
git clone https://github.com/xiaozhiliaoo/jvm-practice
git clone https://github.com/xiaozhiliaoo/j2eepattern-practice
git clone https://github.com/xiaozhiliaoo/poeaa-practice
git clone https://github.com/xiaozhiliaoo/concurrency-practice
git clone https://github.com/xiaozhiliaoo/jmh-practice
git clone https://github.com/xiaozhiliaoo/distributed-practice
git clone https://github.com/xiaozhiliaoo/algorithm-practice
git clone https://github.com/xiaozhiliaoo/rpc-practice
git clone https://github.com/xiaozhiliaoo/nginx-practice
git clone https://github.com/xiaozhiliaoo/zookeeper-practice
git clone https://github.com/xiaozhiliaoo/netty-practice
git clone https://github.com/xiaozhiliaoo/mq-practice
git clone https://github.com/xiaozhiliaoo/kv-store-pracitce
git clone https://github.com/xiaozhiliaoo/sharding-practice
git clone https://github.com/xiaozhiliaoo/storm-practice
git clone https://github.com/xiaozhiliaoo/search-practice
git clone https://github.com/xiaozhiliaoo/mysql-practice
git clone https://github.com/xiaozhiliaoo/data-access-practice
git clone https://github.com/xiaozhiliaoo/interface21
git clone https://github.com/xiaozhiliaoo/ioc-practice
git clone https://github.com/xiaozhiliaoo/interviews
git clone https://github.com/xiaozhiliaoo/KnowledgeSystem
git clone https://github.com/xiaozhiliaoo/geektime-notes
git clone https://github.com/xiaozhiliaoo/reading-notes
git clone https://github.com/xiaozhiliaoo/animal-shark
git clone https://github.com/xiaozhiliaoo/go-probabilistic-ds-practice
git clone https://github.com/xiaozhiliaoo/operating-system-practice
git clone https://github.com/xiaozhiliaoo/database-system-practice
git clone https://github.com/xiaozhiliaoo/compliers-practice
git clone https://github.com/xiaozhiliaoo/my-collectbook
git clone https://github.com/xiaozhiliaoo/performance-practice.git
git clone https://github.com/xiaozhiliaoo/develop-tools-practice
git clone https://github.com/xiaozhiliaoo/architecture-practice
git clone https://github.com/xiaozhiliaoo/continuous-inspection-practice
git clone https://github.com/xiaozhiliaoo/project-management-practice.git
git clone https://github.com/xiaozhiliaoo/refactor.git
git clone https://github.com/xiaozhiliaoo/java-security-practice
git clone https://github.com/xiaozhiliaoo/shell-practice
git clone https://github.com/xiaozhiliaoo/blockchain-practice
git clone https://github.com/xiaozhiliaoo/microservice-practice.git
git clone https://github.com/xiaozhiliaoo/research-notes.git