#!/usr/bin/env bash
git clone https://github.com/xiaozhiliaoo/akka-practice.git
git clone https://github.com/xiaozhiliaoo/algorithm-practice.git
git clone https://github.com/xiaozhiliaoo/animal-framework.git
git clone https://github.com/xiaozhiliaoo/animal-magpie.git
git clone https://github.com/xiaozhiliaoo/animal-sc-project.git
git clone https://github.com/xiaozhiliaoo/animal-shark.git
git clone https://github.com/xiaozhiliaoo/animal-tiger.git
git clone https://github.com/xiaozhiliaoo/apue.3e-practice.git
git clone https://github.com/xiaozhiliaoo/architecture-practice.git
git clone https://github.com/xiaozhiliaoo/cassandra-practice.git
git clone https://github.com/xiaozhiliaoo/cicd-practice.git
git clone https://github.com/xiaozhiliaoo/commerce-practice.git
git clone https://github.com/xiaozhiliaoo/compute-infra-practice.git
git clone https://github.com/xiaozhiliaoo/compliers-practice.git
git clone https://github.com/xiaozhiliaoo/compute-infra-practice.git
git clone https://github.com/xiaozhiliaoo/computer-system-practice.git
git clone https://github.com/xiaozhiliaoo/concurrency-practice.git
git clone https://github.com/xiaozhiliaoo/continuous-inspection-practice.git
git clone https://github.com/xiaozhiliaoo/courseop-tech-learning.git
git clone https://github.com/xiaozhiliaoo/cplusplus-primer.git
git clone https://github.com/xiaozhiliaoo/data-access-practice.git
git clone https://github.com/xiaozhiliaoo/data-warehouse-practice.git
git clone https://github.com/xiaozhiliaoo/database-system-practice.git
git clone https://github.com/xiaozhiliaoo/develop-tools-practice.git
git clone https://github.com/xiaozhiliaoo/distributed-scheduling-practice.git
git clone https://github.com/xiaozhiliaoo/distributed-system-practice.git
git clone https://github.com/xiaozhiliaoo/distributed-transaction-practice.git
git clone https://github.com/xiaozhiliaoo/docker-practice.git
git clone https://github.com/xiaozhiliaoo/effective-java-practice.git
git clone https://github.com/xiaozhiliaoo/etcd-raft.git
git clone https://github.com/xiaozhiliaoo/etcd-raftexample.git
git clone https://github.com/xiaozhiliaoo/exchange-tech-learning.git
git clone https://github.com/xiaozhiliaoo/flink-practice.git
git clone https://github.com/xiaozhiliaoo/gateway-sample2.git
git clone https://github.com/xiaozhiliaoo/geektime-ELK.git
git clone https://github.com/xiaozhiliaoo/go-kv-practice.git
git clone https://github.com/xiaozhiliaoo/go-practice.git
git clone https://github.com/xiaozhiliaoo/go-probabilistic-ds-practice.git
git clone https://github.com/xiaozhiliaoo/gradle-practice.git
git clone https://github.com/xiaozhiliaoo/graph-db-practice.git
git clone https://github.com/xiaozhiliaoo/GroovyBooks.git
git clone https://github.com/xiaozhiliaoo/grpc-go-practice.git
git clone https://github.com/xiaozhiliaoo/guava-collections-reading.git
git clone https://github.com/xiaozhiliaoo/guava-concurrency-reading.git
git clone https://github.com/xiaozhiliaoo/hazelcast-raft.git
git clone https://github.com/xiaozhiliaoo/i-heart-logs-cn.git
git clone https://github.com/xiaozhiliaoo/interface21.git
git clone https://github.com/xiaozhiliaoo/interviews.git
git clone https://github.com/xiaozhiliaoo/io-reading.git
git clone https://github.com/xiaozhiliaoo/ioc-practice.git
git clone https://github.com/xiaozhiliaoo/j2ee-practice.git
git clone https://github.com/xiaozhiliaoo/j2eepattern-practice.git
git clone https://github.com/xiaozhiliaoo/java-base-practice.git
git clone https://github.com/xiaozhiliaoo/java-function-stream-reading.git
git clone https://github.com/xiaozhiliaoo/java-lang-reading.git
git clone https://github.com/xiaozhiliaoo/java-security-practice.git
git clone https://github.com/xiaozhiliaoo/javascript-practice.git
git clone https://github.com/xiaozhiliaoo/jcf-reading.git
git clone https://github.com/xiaozhiliaoo/jmh-practice.git
git clone https://github.com/xiaozhiliaoo/juc-reading.git
git clone https://github.com/xiaozhiliaoo/jvm-practice.git
git clone https://github.com/xiaozhiliaoo/k8s-practice.git
git clone https://github.com/xiaozhiliaoo/kafka-streams-in-action.git
git clone https://github.com/xiaozhiliaoo/kv-store-practice.git
git clone https://github.com/xiaozhiliaoo/lambda-practice.git
git clone https://github.com/xiaozhiliaoo/linux-practice.git
git clone https://github.com/xiaozhiliaoo/logging-practice.git
git clone https://github.com/xiaozhiliaoo/lsp-practice.git
git clone https://github.com/xiaozhiliaoo/math-problem.git
git clone https://github.com/xiaozhiliaoo/maven-practice.git
git clone https://github.com/xiaozhiliaoo/meetup.git
git clone https://github.com/xiaozhiliaoo/microservice-practice.git
git clone https://github.com/xiaozhiliaoo/mongodb-practice.git
git clone https://github.com/xiaozhiliaoo/monitor-base.git
git clone https://github.com/xiaozhiliaoo/mq-practice.git
git clone https://github.com/xiaozhiliaoo/my-collect.git
git clone https://github.com/xiaozhiliaoo/my-slides.git
git clone https://github.com/xiaozhiliaoo/mybatis-generator.git
git clone https://github.com/xiaozhiliaoo/mybatis-practice.git
git clone https://github.com/xiaozhiliaoo/mysql-practice.git
git clone https://github.com/xiaozhiliaoo/netty-practice.git
git clone https://github.com/xiaozhiliaoo/network-practice.git
git clone https://github.com/xiaozhiliaoo/news_feed.git
git clone https://github.com/xiaozhiliaoo/webserver-practice.git
git clone https://github.com/xiaozhiliaoo/nodejs-practice.git
git clone https://github.com/xiaozhiliaoo/operating-system-practice.git
git clone https://github.com/xiaozhiliaoo/pattern-practice.git
git clone https://github.com/xiaozhiliaoo/performance-practice.git
git clone https://github.com/xiaozhiliaoo/PLP3.git
git clone https://github.com/xiaozhiliaoo/poeaa-practice.git
git clone https://github.com/xiaozhiliaoo/practice-hub.git
git clone https://github.com/xiaozhiliaoo/programming-language.git
git clone https://github.com/xiaozhiliaoo/project-management-practice.git
git clone https://github.com/xiaozhiliaoo/python-practice.git
git clone https://github.com/xiaozhiliaoo/raft4j.git
git clone https://github.com/xiaozhiliaoo/reactive-practice.git
git clone https://github.com/xiaozhiliaoo/reading-notes.git
git clone https://github.com/xiaozhiliaoo/recommend-system.git
git clone https://github.com/xiaozhiliaoo/refactor.git
git clone https://github.com/xiaozhiliaoo/refactor-practice.git
git clone https://github.com/xiaozhiliaoo/research-notes.git
git clone https://github.com/xiaozhiliaoo/resume.git
git clone https://github.com/xiaozhiliaoo/rpc-practice.git
git clone https://github.com/xiaozhiliaoo/rust-practice.git
git clone https://github.com/xiaozhiliaoo/RustBooks.git
git clone https://github.com/xiaozhiliaoo/ScalaBooks.git
git clone https://github.com/xiaozhiliaoo/search-practice.git
git clone https://github.com/xiaozhiliaoo/servlet-practice.git
git clone https://github.com/xiaozhiliaoo/sfpc-practice.git
git clone https://github.com/xiaozhiliaoo/sharding-practice.git
git clone https://github.com/xiaozhiliaoo/shell-practice.git
git clone https://github.com/xiaozhiliaoo/software-engineering-practice.git
git clone https://github.com/xiaozhiliaoo/sonar-java-rules.git
git clone https://github.com/xiaozhiliaoo/spring-mvc-reading.git
git clone https://github.com/xiaozhiliaoo/spring-project-skeleton.git
git clone https://github.com/xiaozhiliaoo/spring-reading.git
git clone https://github.com/xiaozhiliaoo/spring-test-practice.git
git clone https://github.com/xiaozhiliaoo/spring-training-base.git
git clone https://github.com/xiaozhiliaoo/storage-infra-practice.git
git clone https://github.com/xiaozhiliaoo/storm-practice.git
git clone https://github.com/xiaozhiliaoo/task-schedule-practice.git
git clone https://github.com/xiaozhiliaoo/tdd-practice.git
git clone https://github.com/xiaozhiliaoo/tech-quotes.git
git clone https://github.com/xiaozhiliaoo/test-practice.git
git clone https://github.com/xiaozhiliaoo/thinkinginjava-practice.git
git clone https://github.com/xiaozhiliaoo/tomcat-reading.git
git clone https://github.com/xiaozhiliaoo/tracing-practice.git
git clone https://github.com/xiaozhiliaoo/translate-practice.git
git clone https://github.com/xiaozhiliaoo/validator-practice.git
git clone https://github.com/xiaozhiliaoo/websocket-practice.git
git clone https://github.com/xiaozhiliaoo/wiser-search-engine.git
git clone https://github.com/xiaozhiliaoo/xiaozhiliaoo.git
git clone https://github.com/xiaozhiliaoo/zookeeper-practice.git